version: '3'

services:
    postgres:
      build: ./postgres
      container_name: postgres
      image: "postgres:13.3"
      ports:
        - 5432:5432
      environment:
        - TZ=Asia/Seoul
        - POSTGRES_DB=testpjt
        - POSTGRES_USERNAME=padmin
        - POSTGRES_PASSWORD=padmin
      # volumes:
      #   - postgres:/var/lib/postgresql/data
      #   - ./postgres/init/:/docker-entrypoint-initdb.d/

# volumes:
#   postgres: {}