-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
-- DROP DATABASE IF EXISTS testpjt  CASCADE ;
CREATE ROLE master;
CREATE ROLE backend_dev;
CREATE USER padmin ENCRYPTED PASSWORD 'padmin';
CREATE SCHEMA IF NOT EXISTS testpjt;

CREATE TABLE testpjt.account
(
    idx serial NOT NULL,
    email character varying NOT NULL,
    passwd character varying NOT NULL,
    age character varying NOT NULL,
    username character varying NOT NULL,
    PRIMARY KEY (idx)
);

-- GRANT ALL PRIVILEGES ON DATABASE testpjt TO padmin;
GRANT ALL PRIVILEGES ON SCHEMA testpjt TO master;
GRANT USAGE ON SCHEMA testpjt TO master;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA testpjt TO master;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA testpjt TO master;

-- Grant Role to user
GRANT master TO padmin;

END;